- name: Install required base packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - pip
    - git
    - python-mysqldb
    - zip
    - unzip

- name: wait for ssh
  hosts: localhost
  gather_facts: no

  tasks:
    - local_action: wait_for port=22 host="{{ ip }}" search_regex=OpenSSH delay=10

- name: Install nginx
  apt: name=nginx state=present

- name: Copy across new nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

