- include: root.yml
- include: database.yml
- include: user.yml

- name: install mysql-server
  apt: pkg=mysql-server state=latest

- name: install mysql-client
  apt: pkg=mysql-client state=latest

- name: generate mysql root password
  shell: mkpasswd --method=SHA-256 password
  register: mysql_root_password

- name: install python-mysqldb
  apt: pkg=python-mysqldb  state=latest

- name: Start the MySQL service
  action: service name=mysql state=started

- name: delete anonymous MySQL server user
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

#Test fixing MySQl issue with Pythong - The MySQL-python module is required. 

- name: Install packages required for ansible mysql modules on Ubuntu before 16.04
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
  when: ansible_lsb.major_release|int < 16

- name: Install packages required for ansible mysql modules on Ubuntu 16.04
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - libmysqlclient-dev
  when: ansible_lsb.major_release|int >= 16

- name: Install Python package manager on Ubuntu 16.04
  apt: name=python3-pip state=present
  when: ansible_lsb.major_release|int >= 16

- name: Install the Python package required for ansible MySQL modules on Ubuntu 16.04
  pip: name=mysqlclient
  when: ansible_lsb.major_release|int >= 16
